# Copyright 2010 The Go Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=tour/stack

GOFILES=\
	stack.go\

include $(GOROOT)/src/Make.pkg
